const S = {
    ACCEPT_TERMS: 'Accept Terms Of Use',
    ACCOUNT_EMAIL: 'Account Email',
    ACCOUNT_KEY: 'Account Key',
    ACCOUNT_NAME: 'Account Name',
    ACCOUNT_USERNAME: 'Account Username',
    ADD: 'Add',
    ADD_CONTACT: 'Add Contact',
    ADD_CONTACTS: 'Add Contacts',
    ADD_PHOTO: 'Add Photo',
    ALLOW_ACCESS: 'Allow Access',
    AK_CONFIRMATION: 'AK Confirmation',
    BACK: 'Back',
    BULK_SELECT: 'Bulk Select',
    CANCEL: 'Cancel',
    CAROUSEL_CARD_1: 'Carousel Card 1',
    CAROUSEL_CARD_2: 'Carousel Card 2',
    CAROUSEL_CARD_3: 'Carousel Card 3',
    CLEAR_TEXT: 'Clear Text',
    CLOSE_DIALOG: 'Close Dialog',
    CONFIRMED: 'Confirmed',
    CONTACT_LIST: 'Contact List',
    CONTACT_LIST_ITEM: 'Contact List Item',
    COPY: 'Copy',
    CREATE: 'Create',
    CREATE_ACCOUNT: 'Create Account',
    DECLINE_TERMS: 'Decline Terms Of Use',
    DOWNLOAD: 'Download',
    DURATION: 'Duration',
    EMAIL: 'Email',
    ERROR: 'Error',
    ERROR_TYPE: 'Error Type',
    FALSE: 'false',
    FINISH_ACCOUNT_CREATION: 'Finish Account Creation',
    FINISH_SIGN_UP: 'Finish Sign Up',
    FIRST_NAME: 'First Name',
    INDIVIDUAL: 'Individual',
    INVITE_CONTACT: 'Invite Contact',
    INVITE_CONTACTS: 'Invite Contacts',
    IN_FOCUS: 'In Focus',
    GET_STARTED: 'Get Started',
    LAST_NAME: 'Last Name',
    LEFT: 'Left',
    LAW_ENFORCEMENT_GUIDE: 'Law Enforcement Guide',
    NAVIGATE: 'Navigate',
    NEXT: 'Next',
    NEWSLETTER: 'Newsletter',
    OK: 'OK',
    ONBOARDING: 'Onboarding',
    OS_DIALOG: 'OS Dialog',
    PICK_USERNAME: 'Pick Username',
    PRIVACY_POLICY: 'Privacy Policy',
    READ_MORE: 'Read More',
    RECEIVE_EMAIL: 'Receive Email',
    REQUIRED: 'Required',
    RIGHT: 'Right',
    SAVED: 'Saved',
    SELECT: 'Select',
    SET_SETTING: 'Set Setting',
    SHARE_DATA: 'Share Data',
    SIGN_IN: 'Sign In',
    SIGN_UP: 'Sign Up',
    SKIP: 'Skip',
    START_ACCOUNT_CREATION: 'Start Account Creation',
    SWIPE: 'Swipe',
    SYNC_CONTACTS: 'Sync Contacts',
    TERMS_OF_SERVICE: 'Terms Of Service',
    TERMS_OF_USE: 'Terms Of Use',
    TEXT_INPUT: 'Text Input',
    TOGGLE_VISIBILITY: 'Toggle Visibility',
    TRUE: 'true',
    USERNAME: 'Username',
    VIA_SYNC: 'Via Sync',
    VIEW_LINK: 'View Link',
    WELCOME_SCREEN: 'Welcome Screen',
    WHERE_ACCOUNT_KEY: 'Where to find Account Key'
};

export default S;
