const S = {
    ACCOUNT_KEY: 'Account Key',
    WHERE_ACCOUNT_KEY: 'Where to find Account Key',
    ADD_PHOTO: 'Add Photo',
    AK_CONFIRMATION: 'AK Confirmation',
    BACK: 'Back',
    CANCEL: 'Cancel',
    CLOSE_DIALOG: 'Close Dialog',
    CONFIRMED: 'Confirmed',
    COPY: 'Copy',
    CREATE_ACCOUNT: 'Create Account',
    DOWNLOAD: 'Download',
    DURATION: 'Duration',
    EMAIL: 'Email',
    ERROR: 'Error',
    ERROR_TYPE: 'Error Type',
    FIRST_NAME: 'First Name',
    IN_FOCUS: 'In Focus',
    GET_STARTED: 'Get Started',
    LAST_NAME: 'Last Name',
    LAW_ENFORCEMENT: 'Law Enforcement',
    NAVIGATE: 'Navigate',
    NEXT: 'Next',
    OK: 'OK',
    ONBOARDING: 'Onboarding',
    PRIVACY_POLICY: 'Privacy Policy',
    REQUIRED: 'Required',
    SAVED: 'Saved',
    SIGN_IN: 'Sign In',
    SIGN_UP: 'Sign Up',
    START_ACCOUNT_CREATION: 'Start Account Creation',
    TERMS_OF_SERVICE: 'Terms Of Service',
    TEXT_INPUT: 'Text Input',
    TOGGLE_VISIBILITY: 'Toggle Visibility',
    USERNAME: 'Username',
    VIEW_LINK: 'View Link'
};

module.exports = S;
